/**
 * Combat Information 
 *      - When user clicks on an ability or constellation, change the lightbox information
 *      - Change the abilities and constellation information below based on the character
 */

const combatInfo = [
    {
        name: "Origin", 
        description: "Normal Attack: Performs up to 5 consecutive spear strikes. <br>\
        Charged Attack: Consumes a certain amount of Stamina to perform an upward slash. <br>\
        Plunging Attack: Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
        video: "./ganyu/combat/Liutian_Archery_Charged.mp4"
        
    },
    {
        name: "Transcendence: Baleful Omen", 
        description: "The Raiden Shogun unveils a shard of her Euthymia, dealing <strong>Electro DMG</strong> to nearby opponents, and granting nearby party members the Eye of Stormy Judgment. <br>\
        Eye of Stormy Judgment <br> \
        When characters with this buff attack and deal DMG to opponents, the Eye will unleash a coordinated attack, dealing <strong>AoE Electro DMG</strong> at the opponent's position. <br>\
        Characters who gain the Eye of Stormy Judgment will have their Elemental Burst DMG increased based on the Energy Cost of the Elemental Burst during the Eye's duration. The Eye can \
        initiate one coordinated attack every 0.9s per party. Coordinated attacks generated by characters not controlled by you deal 20% of the normal DMG.",
        video: "./ganyu/combat/Trail_of_the_Qilin.mp4"
    },
    {
        name: "Secret Art: Musou Shinsetsu",
        description: "Coalesces atmospheric frost and snow to summon a Sacred Cryo Pearl that exorcises evil.<br>\
                    During its ability duration, the Sacred Cryo Pearl will continuously rain down shards of ice, \
                    striking opponents within an AoE and dealing <strong>Cryo DMG</strong>.",
        video: "./ganyu/combat/Celestial_Shower.mp4"
    },
    {
        name: "Wishes Unnumbered",
        description: "After firing a Frostflake Arrow, the CRIT Rate of subsequent Frostflake Arrows and their \
        resulting bloom effects is increased by <strong>20%</strong> for 5s.",
    },
    {
        name: "Enlightened One",
        description: "Celestial Shower grants a 20% <strong>Cryo DMG Bonus</strong> to active members in the AoE."
    },
    {
        name: "All-Preserver",
        description: "Refunds <strong>15%</strong> of the ores used when crafting Bow-type weapons.",
        video: "./ganyu/combat/Preserved_for_the_Hunt.mp4"
    }
]

const constellationInfo = [
    {
        name: "Ominous Inscription", 
        description: "Chakra Desiderata will gather Resolve even faster. When Electro characters use their Elemental \
        Bursts, the Resolve gained is increased by 80%. When characters of other Elemental Types use their Elemental \
        Bursts, the Resolve gained is increased by 20%."
    },
    {
        name: "Steelbreaker",
        description: "While using Musou no Hitotachi and in the Musou Isshin state applied by Secret Art: Musou Shinsetsu, \
        the Raiden Shogun's attacks ignore 60% of opponents's DEF."
    },
    {
        name: "Shinkage Bygones",
        description: "Increases the Level of Secret Art: Musou Shinsetsu by 3. Maximum upgrade level is 15."
    },
    {
        name: "Pledge of Propriety",
        description: "When the Musou Isshin state applied by Secret Art: Musou Shinsetsu expires, all nearby party members \
        (excluding the Raiden Shogun) gain 30% bonus ATK for 10s."
    },
    {
        name: "Shogun's Descent",
        description: "Increases the Level of Transcendence: Baleful Omen by 3. Maximum upgrade level is 15."
    },
    {
        name: "Wishbearer",
        description: "While in the Musou Isshin state applied by Secret Art: Musou Shinsetsu, attacks by the Raiden Shogun that \
        are considered part of her Elemental Burst will decrease all nearby party members' (but not including the Raiden Shogun herself) \
        Elemental Burst CD by 1s when they hit opponents. This effect can trigger once every 1s, and can trigger a total of 5 times during \
        the state's duration."
    }
]

// Get titles from dom 
const abilityTitle = document.getElementById("ability-title");
const constellationTitle = document.getElementById("constellation-title");

// Get images from dom
const abilityImages = [...document.getElementById("abilities").children];
const constellationImages = [...document.getElementById("constellations").children];

// Animation: Exit 
document.getElementById("combat-exit").addEventListener("click", () =>{
    document.getElementById("combat-overlay").style.opacity = "0";
    document.getElementById("abilities-constellation").style.opacity = "1";
    document.getElementById("combat-overlay").style.zIndex = "-1";
});

// Loop through each ability 
for(let i = 0; i < abilityImages.length; i++){
    
    // Animation Enlarge Ability
    abilityImages[i].addEventListener("mouseover", () =>{
        abilityImages[i].style.transform = "scale(1.05)";
        abilityTitle.innerHTML = combatInfo[i].name;
    });
    abilityImages[i].addEventListener("mouseout", () =>{
        abilityImages[i].style.transform = "scale(1)";
    });


    abilityImages[i].addEventListener("click", () =>{

        // Change Title and Description
        document.getElementById("combat-title").innerHTML = combatInfo[i].name;
        document.getElementById("combat-description").innerHTML = combatInfo[i].description;

        // Change Video
        if(combatInfo[i].hasOwnProperty('video')){
            document.getElementById("combat-video").firstElementChild.src = combatInfo[i].video;
        }
        else{
            document.getElementById("combat-video").firstElementChild.style.display = "none";
        }
        

        // Animation
        document.getElementById("combat-overlay").style.zIndex = "2";
        document.getElementById("combat-overlay").style.opacity = "1";
        document.getElementById("abilities-constellation").style.opacity = "0";
        document.getElementById("combat-video").style.display = "block";

    });

    // Animation: Enlarge Constellation
    constellationImages[i].addEventListener("mouseover", () =>{
        constellationImages[i].style.transform = "scale(1.05)";
        constellationTitle.innerHTML = constellationInfo[i].name;
    });
    constellationImages[i].addEventListener("mouseout", () =>{
        constellationImages[i].style.transform = "scale(1)";
    });

    constellationImages[i].addEventListener("click", () =>{
        // Change Title and Description 
        document.getElementById("combat-title").innerHTML = constellationInfo[i].name;
        document.getElementById("combat-description").innerHTML = constellationInfo[i].description;

        // Animation
        document.getElementById("combat-overlay").style.zIndex = "2";
        document.getElementById("combat-overlay").style.opacity = "1";
        document.getElementById("abilities-constellation").style.opacity = "0";
        document.getElementById("combat-video").style.display = "none";
    });

}


